// Hand-drawn artwork supplied for specific festivals/holidays, keyed by
// festival id (see packages/panjika-core/src/festivals.ts) or, for the
// three special tithis that aren't tied to a festival record, by a fixed
// pseudo-key. Falls back to the generic SVG icon set (festivalIcons.tsx)
// for anything not listed here. Multiple images for one key are shown as
// a slow auto-cycling crossfade (see CyclingImage.tsx).

const BASE = "/festival-icons";

export const FESTIVAL_IMAGES: Record<string, string[]> = {
  "poila-boishakh": [`${BASE}/poila-boishakh-1.png`, `${BASE}/poila-boishakh-2.png`],
  "rath-yatra": [`${BASE}/rath-yatra.png`],
  "ulto-rath": [`${BASE}/rath-yatra.png`],
  "guru-purnima": [`${BASE}/guru-purnima.png`],
  "jhulan-yatra": [`${BASE}/jhulan-yatra.png`],
  "rakhi-purnima": [`${BASE}/rakhi-purnima.png`],
  "janmashtami": [`${BASE}/janmashtami.png`],
  "ganesh-chaturthi": [`${BASE}/ganesh-chaturthi.png`],
  "vishwakarma-puja": [`${BASE}/vishwakarma-puja.png`],
  "mahalaya": [`${BASE}/mahalaya.png`],
  "maha-shashthi": [`${BASE}/durga-puja.png`],
  "maha-saptami": [`${BASE}/durga-puja.png`],
  "maha-ashtami": [`${BASE}/durga-puja.png`],
  "maha-nabami": [`${BASE}/durga-puja.png`],
  "vijaya-dashami": [`${BASE}/durga-puja.png`],
  "kojagari-lakshmi-puja": [`${BASE}/lakshmi.png`],
  "kali-puja": [`${BASE}/kali-puja.png`],
  "bhai-phota": [`${BASE}/bhai-phota.png`],
  "chhath-puja": [`${BASE}/chhath-puja.png`],
  "rash-purnima": [`${BASE}/rash-purnima.png`],
  "saraswati-puja": [`${BASE}/saraswati-puja.png`],
  "shivratri": [`${BASE}/shiva.png`],
  "dol-purnima": [`${BASE}/dol-purnima.png`],
  "annapurna-puja": [`${BASE}/lakshmi.png`],
  "charak-gajan": [`${BASE}/shiva.png`],

  "new-year": [`${BASE}/new-year.png`],
  "republic-day": [`${BASE}/republic-day.png`],
  "valentines-day": [`${BASE}/valentines-day.png`],
  "independence-day": [`${BASE}/independence-day.png`],
  "teachers-day": [`${BASE}/teachers-day.png`],
  "radhakrishnan-jayanti": [`${BASE}/teachers-day.png`],
  "radhakrishnan-tirodhan": [`${BASE}/teachers-day.png`],
  "gandhi-jayanti": [`${BASE}/gandhi-jayanti.png`],
  "childrens-day": [`${BASE}/childrens-day.png`],
  "christmas-eve": [`${BASE}/christmas-eve.png`],
  "christmas": [`${BASE}/christmas.png`],
  "good-friday": [`${BASE}/good-friday.png`],
  "easter-sunday": [`${BASE}/easter-sunday.png`],

  "eid-ul-fitr": [`${BASE}/eid-ul-fitr.png`],
  "eid-ul-adha": [`${BASE}/eid-ul-adha.png`],
  "shab-e-barat": [`${BASE}/shab-e-barat.png`],
  "muharram": [`${BASE}/muharram.png`],

  "rabindra-jayanti": [`${BASE}/rabindranath.png`],
  "rabindra-tirodhan": [`${BASE}/rabindranath.png`],
  "ramakrishna-jayanti": [`${BASE}/ramakrishna.png`],
  "ramakrishna-tirodhan": [`${BASE}/ramakrishna.png`],
  "vivekananda-jayanti": [`${BASE}/vivekananda.png`],
  "vivekananda-tirodhan": [`${BASE}/vivekananda.png`],
  "sarada-devi-jayanti": [`${BASE}/sarada-devi.png`],
  "sarada-devi-tirodhan": [`${BASE}/sarada-devi.png`],

  "vidyasagar-jayanti": [`${BASE}/vidyasagar.png`],
  "vidyasagar-tirodhan": [`${BASE}/vidyasagar.png`],
  "netaji-jayanti": [`${BASE}/netaji.png`],

  "buddha-purnima": [`${BASE}/buddha-purnima.png`],
  "ram-navami": [`${BASE}/ram-navami.png`],
  "mahavir-jayanti": [`${BASE}/mahavir-jayanti.png`],
  "hanuman-jayanti": [`${BASE}/hanuman-jayanti.png`],
  "chaitanya-mahaprabhu-jayanti": [`${BASE}/chaitanya-mahaprabhu.png`],
  "guru-nanak-jayanti": [`${BASE}/guru-nanak.png`],
  "harichand-thakur-jayanti": [`${BASE}/harichand-thakur.png`],
  "harichand-thakur-tirodhan": [`${BASE}/harichand-thakur.png`],
  "lokenath-jayanti": [`${BASE}/lokenath-brahmachari.png`],
  "lokenath-tirodhan": [`${BASE}/lokenath-brahmachari.png`],

  "ambedkar-jayanti": [`${BASE}/ambedkar.png`],
  "ambedkar-tirodhan": [`${BASE}/ambedkar.png`],
  "ashutosh-mukherjee-jayanti": [`${BASE}/ashutosh-mukherjee.png`],
  "ashutosh-mukherjee-tirodhan": [`${BASE}/ashutosh-mukherjee.png`],
  "bal-gangadhar-tilak-jayanti": [`${BASE}/bal-gangadhar-tilak.png`],
  "bal-gangadhar-tilak-tirodhan": [`${BASE}/bal-gangadhar-tilak.png`],
  "bankim-chandra-jayanti": [`${BASE}/bankim-chandra.png`],
  "bankim-chandra-tirodhan": [`${BASE}/bankim-chandra.png`],
  "bibhutibhushan-jayanti": [`${BASE}/bibhutibhushan.png`],
  "bibhutibhushan-tirodhan": [`${BASE}/bibhutibhushan.png`],
  "bidhan-chandra-roy-day": [`${BASE}/bidhan-chandra-roy.png`],
  "chittaranjan-das-jayanti": [`${BASE}/chittaranjan-das.png`],
  "chittaranjan-das-tirodhan": [`${BASE}/chittaranjan-das.png`],
  "abdul-kalam-jayanti": [`${BASE}/abdul-kalam.png`],
  "abdul-kalam-tirodhan": [`${BASE}/abdul-kalam.png`],
  "khudiram-bose-jayanti": [`${BASE}/khudiram-bose.png`],
  "khudiram-bose-tirodhan": [`${BASE}/khudiram-bose.png`],
  "meghnad-saha-jayanti": [`${BASE}/meghnad-saha.png`],
  "meghnad-saha-tirodhan": [`${BASE}/meghnad-saha.png`],
  "nehru-jayanti": [`${BASE}/jawaharlal-nehru.png`],
  "nehru-tirodhan": [`${BASE}/jawaharlal-nehru.png`],
  "prafulla-chandra-ray-jayanti": [`${BASE}/prafulla-chandra-ray.png`],
  "prafulla-chandra-ray-tirodhan": [`${BASE}/prafulla-chandra-ray.png`],
  "sharat-chandra-jayanti": [`${BASE}/sharat-chandra.png`],
  "sharat-chandra-tirodhan": [`${BASE}/sharat-chandra.png`],
  "sukumar-ray-jayanti": [`${BASE}/sukumar-ray.png`],
  "sukumar-ray-tirodhan": [`${BASE}/sukumar-ray.png`],
  "surendranath-banerjee-jayanti": [`${BASE}/surendranath-banerjee.png`],
  "surendranath-banerjee-tirodhan": [`${BASE}/surendranath-banerjee.png`],
  "surya-sen-jayanti": [`${BASE}/surya-sen.png`],
  "surya-sen-tirodhan": [`${BASE}/surya-sen.png`],
  "mother-teresa-jayanti": [`${BASE}/mother-teresa.png`],
  "mother-teresa-tirodhan": [`${BASE}/mother-teresa.png`],
  "bhagat-singh-jayanti": [`${BASE}/bhagat-singh.png`],
  "bhagat-singh-tirodhan": [`${BASE}/bhagat-singh.png`],
  "jibanananda-das-jayanti": [`${BASE}/jibanananda-das.png`],
  "jibanananda-das-tirodhan": [`${BASE}/jibanananda-das.png`],
  "madhusudan-dutta-jayanti": [`${BASE}/madhusudan-dutta.png`],
  "madhusudan-dutta-tirodhan": [`${BASE}/madhusudan-dutta.png`],
};

/** Pseudo-keys for the special-tithi badges (not tied to a Festival record). */
export const TITHI_IMAGES: Record<string, string[]> = {
  ekadashi: [`${BASE}/ekadashi.png`],
  amavasya: [`${BASE}/amavasya.png`],
};
